### PR TITLE
#13 View All Tags

### PR DESCRIPTION
**Pull request by jessicasturgell**
# Description

When an admin is in the app, they can select the Tag Management link in the menu. They will then be directed to a page that lists all Tag names ordered alphabetically. [Trello Ticket #13](https://trello.com/c/fzSD5odJ)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Testing Instructions

- From the command line:
  - `git add` and `git commit` whatever you're working on on your branch
  - `git checkout main`
  - `git fetch --a`
  - `git checkout js-boilerplate`
  - If you don't see the most recent version of my files, `git pull origin js-boilerplate`
- If you haven't created the Tabloid MVC database, please do so.
  - Use this to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-9/tabloidmvc-dalvin-and-the-chipmunks/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
  - Use this to seed the database: [SQL Seed Data](https://github.com/NewForce-Cohort-9/tabloidmvc-dalvin-and-the-chipmunks/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
- Click the execute with debugger solid green button to launch the app
- In browser, please go to Login on the nav bar and log in with this email: admin@example.com
- This should redirect you back to the home page.
- Tag Management should be showing on the nav bar now. Please click this to access the Tag Management page.
- On the Tag Management page, there should be a list of existing tags from the database in alphabetical order.
- Review data and query the Tabloid MVC database to verify that data displayed in the app is accurate using the following SQL statement:
```
SELECT t.Id, t.Name
FROM Tag t
ORDER BY t.Name
```

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Please link the ticket in the description of your PR like in the example in the gist

SQL data steps needs included. Please look at gist testing instructions and make sure yours are as descriptive as that

The SQL statement provided would not give you the tags in alphabetical order. The tester must be able to easily see tags in alphabetical order - you can rectify the SQL statement or you can list them alphabetically.

**Review by sarahebrooks12 — APPROVED** [review]
👼🏻

**Comment by Meowph** [comment]
Looks great Jess!

**Comment by Iris-Lee4** [comment]
Looks good!

**Pull request merged**
